// <auto-generated />
using System;
using JobSite.Core.Data.MainContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobSite.Core.Migrations
{
    [DbContext(typeof(SiteContext))]
    partial class SiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobSite.Domain.Job", b =>
                {
                    b.Property<Guid>("JobId");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("RecruiterId");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("JobId")
                        .HasName("PK_Jobs");

                    b.HasIndex("RecruiterId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("JobSite.Domain.Recruiter", b =>
                {
                    b.Property<Guid>("RecruiterId");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RecruiterName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("Updated");

                    b.HasKey("RecruiterId")
                        .HasName("PK_Recruiters");

                    b.ToTable("Recruiter");
                });

            modelBuilder.Entity("JobSite.Domain.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("SiteId");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            SiteId = 1,
                            SiteName = "InterNurse",
                            ThemeName = "internurse"
                        },
                        new
                        {
                            SiteId = 2,
                            SiteName = "UkVets",
                            ThemeName = "ukvets"
                        },
                        new
                        {
                            SiteId = 3,
                            SiteName = "RhineGold",
                            ThemeName = "rhinegold"
                        });
                });

            modelBuilder.Entity("JobSite.Domain.Job", b =>
                {
                    b.HasOne("JobSite.Domain.Recruiter", "Recruiter")
                        .WithMany("RecruiterJobs")
                        .HasForeignKey("RecruiterId")
                        .HasConstraintName("FK_Recruiters_Jobs")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
